name: Reusable Workflow use
on: 
  workflow_dispatch:
jobs:
  do-it:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
      -  name: Run a one-line script
         run: echo Hello Aman
  docker:
    
    uses: aman2575/ArgoCD-NodeApp/.github/workflows/Build_and_Push_Docker_Images.yml@master
    with:
      image_name: node-hello
      tag: $GITHUB_RUN_NUMBER
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

